### ISSUE TITLE
custom event should be kebab case

### ISSUE THREAD

**Issue by kentskyo** [stijlbreuk/vue-color-picker-wheel#6]
colorChange should emit "color-change", otherwise it's impossible to catch the event in dom templates. Thanks!

**Comment by nino-vrijman** [comment]
Hi,
Thanks for your feedback. https://github.com/stijlbreuk/vue-color-picker-wheel/pull/4 implements v-model for the color picker which you can use instead of 'colorChange'. Version 0.3.0 on npm contains that change.

We've been discussing what to do with the 'colorChange' (which indeed should be 'color-change') event and the 'startColor' property. Would you still like to be able to use the 'color-change' event even with v-model implemented?

**Comment by kentskyo** [comment]
ah, v-model should cover it, thanks!

**Comment by nino-vrijman** [comment]
Fixed in https://github.com/stijlbreuk/vue-color-picker-wheel/pull/7, change is published in version 0.4.0.
